services:
  mongo1:
    image: mongo:8
    container_name: mongo1
    # We add a small shell wrapper to the command to run the init script locally
    entrypoint: [
      "/bin/bash", "-c", 
      "mongod --replSet rs0 --bind_ip_all --keyFile /run/secrets/mongo_key & sleep 5; mongosh --file /init-rs.js; wait" ]
    volumes:
      - mongo1_data:/data/db
      - ./init-rs.js:/init-rs.js:ro
    networks:
      - mongo-cluster
    secrets:
      - mongo_key

  mongo2:
    image: mongo:8
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/run/secrets/mongo_key"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo-cluster
    secrets:
      - mongo_key

  mongo3:
    image: mongo:8
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/run/secrets/mongo_key"]
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo-cluster
    secrets:
      - mongo_key

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

secrets:
  mongo_key:
    file: ./secrets/mongo-keyfile