name: mongodb-cluster

services:
  mongo-keygen:
    image: mongo:8
    container_name: mongo-keygen
    hostname: mongo-keygen
    restart: "no"
    entrypoint: ["/bin/bash", "/scripts/mongo-keygen.sh"]
    volumes:
      - mongo_keyfile:/keyfile
      - ./scripts/mongo-keygen.sh:/scripts/mongo-keygen.sh:ro
    networks: [mongo-cluster]

  mongo1:
    image: mongo:8
    container_name: mongo1
    hostname: mongo1
    init: true
    restart: unless-stopped
    depends_on:
      - mongo-keygen
    entrypoint: ["/bin/bash", "/scripts/start-shard-primary.sh"]
    environment:
      MONGO_REPLSET_NAME: rs0
      MONGO_PORT: "27017"
      MONGO_INIT_SCRIPT: /scripts/init-replset.js
      MONGO_BOOTSTRAP_PASSWORD: ${MONGO_BOOTSTRAP_PASSWORD}
      MONGO_KEYFILE_PATH: /run/mongo-keyfile/mongo-keyfile

      MONGO_RS_NAME: rs0
      MONGO_LOCAL_HOST: mongo1:27017
      MONGO_IS_CONFIGSVR: "false"
      MONGO_RS_MEMBERS_JSON: >-
        [{"_id":0,"host":"mongo1:27017","priority":10},
        {"_id":1,"host":"mongo2:27017","priority":1},
        {"_id":2,"host":"mongo3:27017","priority":1}]
      MONGO_OTHER_PRIMARY_GRACE_MS: "10000"
    volumes:
      - mongo1_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
      - ./scripts/start-shard-primary.sh:/scripts/start-shard-primary.sh:ro
      - ./scripts/init-replset.js:/scripts/init-replset.js:ro
    networks: [mongo-cluster]

  mongo2:
    image: mongo:8
    container_name: mongo2
    hostname: mongo2
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs0",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo2_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongo3:
    image: mongo:8
    container_name: mongo3
    hostname: mongo3
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs0",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo3_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongo4:
    image: mongo:8
    container_name: mongo4
    hostname: mongo4
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    entrypoint: ["/bin/bash", "/scripts/start-shard-primary.sh"]
    environment:
      MONGO_REPLSET_NAME: rs1
      MONGO_PORT: "27017"
      MONGO_INIT_SCRIPT: /scripts/init-replset.js
      MONGO_BOOTSTRAP_PASSWORD: ${MONGO_BOOTSTRAP_PASSWORD}
      MONGO_KEYFILE_PATH: /run/mongo-keyfile/mongo-keyfile

      MONGO_RS_NAME: rs1
      MONGO_LOCAL_HOST: mongo4:27017
      MONGO_IS_CONFIGSVR: "false"
      MONGO_RS_MEMBERS_JSON: >-
        [{"_id":0,"host":"mongo4:27017","priority":10},
        {"_id":1,"host":"mongo5:27017","priority":1},
        {"_id":2,"host":"mongo6:27017","priority":1}]
      MONGO_OTHER_PRIMARY_GRACE_MS: "10000"
    volumes:
      - mongo4_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
      - ./scripts/start-shard-primary.sh:/scripts/start-shard-primary.sh:ro
      - ./scripts/init-replset.js:/scripts/init-replset.js:ro
    networks: [mongo-cluster]

  mongo5:
    image: mongo:8
    container_name: mongo5
    hostname: mongo5
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs1",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo5_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongo6:
    image: mongo:8
    container_name: mongo6
    hostname: mongo6
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs1",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo6_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongo7:
    image: mongo:8
    container_name: mongo7
    hostname: mongo7
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    entrypoint: ["/bin/bash", "/scripts/start-shard-primary.sh"]
    environment:
      MONGO_REPLSET_NAME: rs2
      MONGO_PORT: "27017"
      MONGO_INIT_SCRIPT: /scripts/init-replset.js
      MONGO_BOOTSTRAP_PASSWORD: ${MONGO_BOOTSTRAP_PASSWORD}
      MONGO_KEYFILE_PATH: /run/mongo-keyfile/mongo-keyfile

      MONGO_RS_NAME: rs2
      MONGO_LOCAL_HOST: mongo7:27017
      MONGO_IS_CONFIGSVR: "false"
      MONGO_RS_MEMBERS_JSON: >-
        [{"_id":0,"host":"mongo7:27017","priority":10},
        {"_id":1,"host":"mongo8:27017","priority":1},
        {"_id":2,"host":"mongo9:27017","priority":1}]
      MONGO_OTHER_PRIMARY_GRACE_MS: "10000"
    volumes:
      - mongo7_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
      - ./scripts/start-shard-primary.sh:/scripts/start-shard-primary.sh:ro
      - ./scripts/init-replset.js:/scripts/init-replset.js:ro
    networks: [mongo-cluster]

  mongo8:
    image: mongo:8
    container_name: mongo8
    hostname: mongo8
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs2",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo8_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongo9:
    image: mongo:8
    container_name: mongo9
    hostname: mongo9
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet", "rs2",
        "--bind_ip_all",
        "--port", "27017",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - mongo9_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  cfg1:
    image: mongo:8
    container_name: cfg1
    hostname: cfg1
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    entrypoint: ["/bin/bash", "/scripts/start-config-primary.sh"]
    environment:
      MONGO_REPLSET_NAME: cfgRS
      MONGO_PORT: "27019"
      MONGO_INIT_SCRIPT: /scripts/init-replset.js
      MONGO_BOOTSTRAP_PASSWORD: ${MONGO_BOOTSTRAP_PASSWORD}
      MONGO_KEYFILE_PATH: /run/mongo-keyfile/mongo-keyfile
      
      MONGO_RS_NAME: cfgRS
      MONGO_LOCAL_HOST: cfg1:27019
      MONGO_IS_CONFIGSVR: "true"
      MONGO_RS_MEMBERS_JSON: >-
        [{"_id":0,"host":"cfg1:27019","priority":10},
        {"_id":1,"host":"cfg2:27019","priority":1},
        {"_id":2,"host":"cfg3:27019","priority":1}]
    volumes:
      - cfg1_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
      - ./scripts/start-config-primary.sh:/scripts/start-config-primary.sh:ro
      - ./scripts/init-replset.js:/scripts/init-replset.js:ro
    networks: [mongo-cluster]

  cfg2:
    image: mongo:8
    container_name: cfg2
    hostname: cfg2
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet", "cfgRS",
        "--bind_ip_all",
        "--port", "27019",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - cfg2_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  cfg3:
    image: mongo:8
    container_name: cfg3
    hostname: cfg3
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet", "cfgRS",
        "--bind_ip_all",
        "--port", "27019",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    volumes:
      - cfg3_data:/data/db
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  mongos:
    image: mongo:8
    container_name: mongos
    hostname: mongos
    restart: unless-stopped
    init: true
    depends_on:
      - mongo-keygen
      - cfg1
      - cfg2
      - cfg3
    command:
      [
        "mongos",
        "--bind_ip_all",
        "--port", "27017",
        "--configdb", "cfgRS/cfg1:27019,cfg2:27019,cfg3:27019",
        "--keyFile", "/run/mongo-keyfile/mongo-keyfile"
      ]
    ports:
      - "27018:27017"
    volumes:
      - mongo_keyfile:/run/mongo-keyfile:ro
    networks: [mongo-cluster]

  cluster-bootstrap:
    image: mongo:8
    container_name: cluster-bootstrap
    hostname: cluster-bootstrap
    restart: "no"
    depends_on:
      - mongos
      - mongo1
      - mongo4
      - mongo7
      - cfg1
    entrypoint: ["/bin/bash", "/scripts/bootstrap-cluster.sh"]
    environment:
      MONGO_BOOTSTRAP_PASSWORD: ${MONGO_BOOTSTRAP_PASSWORD}
      MONGO_CLUSTER_ADMIN_PASSWORD: ${MONGO_CLUSTER_ADMIN_PASSWORD}
      MONGO_APP_WRITE_PASSWORD: ${MONGO_APP_WRITE_PASSWORD}
      MONGO_APP_READ_PASSWORD: ${MONGO_APP_READ_PASSWORD}
    volumes:
      - ./scripts/bootstrap-cluster.sh:/scripts/bootstrap-cluster.sh:ro
      - ./scripts/init-cluster.js:/scripts/init-cluster.js:ro
      - ./scripts/init-projectdb.js:/scripts/init-projectdb.js:ro
    networks: [mongo-cluster]

  data-import:
    image: python:3.12-slim
    container_name: data-import
    hostname: data-import
    restart: "no"
    working_dir: /app
    entrypoint: ["bash", "/app/import/run-import.sh"]
    environment:
      MONGO_URI: "mongodb://appWriter:${MONGO_APP_WRITE_PASSWORD}@mongos:27017/projectdb?authSource=projectdb"
      PATIENTS_FILE: "/app/Data/patients.csv"
      ENCOUNTERS_FILE: "/app/Data/encounters.csv"
      CLAIMS_FILE: "/app/Data/claims_and_billing.csv"
      IMPORT_BATCH_SIZE: "1000"
    depends_on:
      - cluster-bootstrap
    volumes:
      - ./Data:/app/Data:ro
      - ./import:/app/import:ro
    networks: [mongo-cluster]
  compass-web:
    image: haohanyang/compass-web:latest
    container_name: compass-web
    hostname: compass-web
    restart: unless-stopped
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      CW_PORT: "8080"
      CW_HOST: "0.0.0.0"
      CW_APP_NAME: "MongoDB Project Compass Web"
      CW_ENABLE_EDIT_CONNECTIONS: "false"
      CW_BASIC_AUTH_USERNAME: ${COMPASS_WEB_USERNAME}
      CW_BASIC_AUTH_PASSWORD: ${COMPASS_WEB_PASSWORD}
      CW_MONGO_URI: "mongodb://clusterAdminUser:${MONGO_CLUSTER_ADMIN_PASSWORD}@mongos:27017/admin?authSource=admin&appName=CompassWeb&name=Semester-Project-Cluster"
    networks: [mongo-cluster]

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo_keyfile:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo4_data:
  mongo5_data:
  mongo6_data:
  mongo7_data:
  mongo8_data:
  mongo9_data:
  cfg1_data:
  cfg2_data:
  cfg3_data: